insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (4, 2, 3, 15, 9, 'Pull ups');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (3, 1, 10, 13, 8, 'Push ups');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (5, 5, 6, 12, 7, 'Squats');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (5, 12, 6, 16, 3, 'Deadlifts');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (5, 12, 6, 16, 3, 'Romanian deadlifts(RDL)');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, name) values (3, 11, 10, 13, 'Bench press');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, name) values (3, 11, 10, 13, 'Inclined bench press');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, fifth_muscle_group_id, name) values (3, 13, 14, 15, 10, 3, 'Overhead press');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, fifth_muscle_group_id, name) values (3, 13, 14, 15, 10, 3, 'Dumbbell shoulder press');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (4, 2, 3, 15, 9, 'Barbell row');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, third_muscle_group_id, fourth_muscle_group_id, name) values (4, 2, 3, 15, 9, 'Dumbbell row');
insert into exercise_templates (exercise_type_id, muscle_group_id, secondary_muscle_group_id, name) values (3, 14, 15, 'Lateral raises');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (5, 7, 'Calf raises');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (4, 3, 'Shrugs');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (4, 9, 'Barbell curls');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (4, 9, 'Dumbbell curls');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (3, 10, 'Dips');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (3, 10, 'Skullcrushers');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (7, 8, 'Sit ups');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (7, 8, 'Crunches');
insert into exercise_templates (exercise_type_id, muscle_group_id, name) values (3, 15, 'Rear delt fly');