ktor:
  application:
    modules:
      - com.tiberiu.wing.ApplicationKt.module
  deployment:
    port: 9292

storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "password"